// OpenNext config for the Cloudflare adapter.
// Without this file at the repo root, `opennextjs-cloudflare build` has
// nothing to build against and the Cloudflare Git integration falls back
// to a default placeholder Worker — which is why the deployed URL was
// showing "Hello World" instead of the actual Next.js app.
//
// ── Why there is NO route/function splitting here (§123) ──
// Splitting heavy routes into separate server functions would be the ideal
// fix for the free-plan "Worker exceeded the size limit of 3 MiB" error,
// but it is not possible with this stack:
//   * @opennextjs/cloudflare v1.20 bundles ONLY `.open-next/server-functions/
//     default` — its build pipeline (dist/cli/build/bundle-server.js) never
//     reads the AWS adapter's `functions: { <name>: { patterns: [...] } }`
//     split config; extra functions would be generated by @opennextjs/aws
//     and then silently never packaged.
//   * This project deploys via Cloudflare's git-integrated "Workers Builds",
//     which runs a single `wrangler deploy` against the ONE entrypoint in
//     wrangler.jsonc ("main": ".open-next/worker.js"). There is no place to
//     attach secondary Workers, so even if functions were split they could
//     not be deployed.
// So the size fight happens one level down instead, in next.config.ts:
//   * serverExternalPackages keeps browser-only giants (pdfjs-dist, epubjs)
//     out of the server bundle entirely (§119).
//   * outputFileTracingExcludes drops sharp/@img native binaries from the
//     file trace (useless on workerd, and their hashed standalone symlinks
//     crash local Windows builds with EPERM).
// Client-side-only libraries stay out of SSR reach via next/dynamic
// ({ ssr: false }) where applicable (e.g. BookReader).
import { defineCloudflareConfig } from "@opennextjs/cloudflare";

export default defineCloudflareConfig({
  // Cold-start CPU saver: don't preload any route modules into the isolate
  // on boot. This is already the default — spelled out explicitly here so
  // nobody "optimizes" cold starts into a size/CPU regression later.
  routePreloadingBehavior: "none",
});

