'use client';

import { useState, useEffect } from 'react';
import { supabase } from '../../lib/supabase';
import { isDeveloperRole } from '../../lib/auth/roles';
import { Lock, Lightbulb, Trash2, Plus, RefreshCw, CheckCircle2, Link2, Users, Sparkles, BookOpen } from 'lucide-react';
import { setPostLoginRedirect } from '../../lib/auth/authRedirect';

// Admin insert UI for `mangal_ideas` company cards (Phase 1, build step 2 —
// see CONTEXT.md §0c). story_demand and audience rows are auto-generated by
// the refresh_mangal_ideas() RPC (§0d-i / phase1_functions migration) and
// are read-only here — this page shows them for visibility only, with a
// manual "Refresh" button since there's no scheduled job yet.

interface MangalIdea {
  id: string;
  type: 'company' | 'story_demand' | 'audience';
  series_id: string | null;
  source_post_id: string | null;
  title: string;
  description: string | null;
  link_url: string | null;
  created_at: string;
}

const TYPE_BADGE: Record<MangalIdea['type'], { label: string; color: string; bg: string; border: string; icon: typeof Sparkles }> = {
  company: { label: 'Company', color: '#f97316', bg: 'rgba(249,115,22,0.10)', border: 'rgba(249,115,22,0.3)', icon: Sparkles },
  story_demand: { label: 'Story demand', color: '#a855f7', bg: 'rgba(168,85,247,0.10)', border: 'rgba(168,85,247,0.3)', icon: BookOpen },
  audience: { label: 'Audience', color: '#10b981', bg: 'rgba(16,185,129,0.10)', border: 'rgba(16,185,129,0.3)', icon: Users },
};

export default function AdminMangalIdeasPage() {
  const [ideas, setIdeas] = useState<MangalIdea[]>([]);
  const [loading, setLoading] = useState(true);
  const [allowed, setAllowed] = useState<boolean | null>(null);

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [linkUrl, setLinkUrl] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);

  const [refreshing, setRefreshing] = useState(false);
  const [refreshMsg, setRefreshMsg] = useState<string | null>(null);

  const [deletingId, setDeletingId] = useState<string | null>(null);

  const loadIdeas = async () => {
    const { data } = await supabase
      .from('mangal_ideas')
      .select('id, type, series_id, source_post_id, title, description, link_url, created_at')
      .order('created_at', { ascending: false });
    if (data) setIdeas(data as MangalIdea[]);
  };

  useEffect(() => {
    const load = async () => {
      const { data: u } = await supabase.auth.getUser();
      if (!u.user) { setPostLoginRedirect(window.location.pathname); window.location.href = '/login'; return; }

      const { data: profile } = await supabase
        .from('profiles')
        .select('role')
        .eq('id', u.user.id)
        .single();

      if (!isDeveloperRole(profile?.role)) {
        setAllowed(false);
        setLoading(false);
        return;
      }
      setAllowed(true);
      await loadIdeas();
      setLoading(false);
    };
    load();
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) { setSubmitError('Title is required.'); return; }
    setSubmitting(true);
    setSubmitError(null);

    const { data: u } = await supabase.auth.getUser();
    const { error } = await supabase.from('mangal_ideas').insert({
      type: 'company',
      title: title.trim(),
      description: description.trim() || null,
      link_url: linkUrl.trim() || null,
      created_by: u.user?.id ?? null,
    });

    if (error) {
      setSubmitError(error.message);
      setSubmitting(false);
      return;
    }

    setTitle(''); setDescription(''); setLinkUrl('');
    setSubmitting(false);
    await loadIdeas();
  };

  const handleDelete = async (id: string) => {
    setDeletingId(id);
    const { error } = await supabase.from('mangal_ideas').delete().eq('id', id);
    if (error) { alert(`Failed to delete: ${error.message}`); setDeletingId(null); return; }
    setIdeas(prev => prev.filter(i => i.id !== id));
    setDeletingId(null);
  };

  const handleRefresh = async () => {
    setRefreshing(true);
    setRefreshMsg(null);
    const { error } = await supabase.rpc('refresh_mangal_ideas');
    if (error) {
      setRefreshMsg(`Failed: ${error.message}`);
      setRefreshing(false);
      return;
    }
    await loadIdeas();
    setRefreshMsg('Story-demand and audience candidates refreshed.');
    setRefreshing(false);
  };

  if (loading) {
    return <div style={{ minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: 'var(--text-muted)' }}>Loading…</div>;
  }

  if (!allowed) {
    return (
      <div style={{ minHeight: '100vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '10px', color: 'var(--text-muted)' }}>
        <Lock size={28} strokeWidth={1.5} />
        <p style={{ fontSize: '14px', margin: 0 }}>You don&apos;t have access to this page.</p>
      </div>
    );
  }

  const companyIdeas = ideas.filter(i => i.type === 'company');
  const otherIdeas = ideas.filter(i => i.type !== 'company');

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg-primary)', padding: '32px 20px' }}>
      <div style={{ maxWidth: '780px', margin: '0 auto' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '6px' }}>
          <Lightbulb size={22} strokeWidth={2} color="#f97316" />
          <h1 style={{ fontSize: '22px', fontWeight: 900, margin: 0, letterSpacing: '-0.02em' }}>Mangal Ideas</h1>
        </div>
        <p style={{ fontSize: '13px', color: 'var(--text-muted)', margin: '0 0 24px' }}>
          Company idea cards surface in the Mangal Ideas feed on KaTube home, alongside
          auto-generated story-demand and audience-idea cards.
        </p>

        {/* ── New company card form ── */}
        <form onSubmit={handleSubmit} style={{
          background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '14px',
          padding: '20px', marginBottom: '28px',
        }}>
          <h2 style={{ fontSize: '14px', fontWeight: 800, margin: '0 0 14px' }}>New company idea card</h2>

          <label style={{ display: 'block', fontSize: '11px', fontWeight: 700, color: 'var(--text-tertiary)', marginBottom: '6px' }}>Title *</label>
          <input
            value={title}
            onChange={e => setTitle(e.target.value)}
            placeholder="e.g. We want a KaTube series set in ancient Kalinga"
            style={{
              width: '100%', padding: '10px 12px', borderRadius: '9px', marginBottom: '14px',
              background: 'var(--bg-input)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', fontSize: '13px',
            }}
          />

          <label style={{ display: 'block', fontSize: '11px', fontWeight: 700, color: 'var(--text-tertiary)', marginBottom: '6px' }}>Description</label>
          <textarea
            value={description}
            onChange={e => setDescription(e.target.value)}
            rows={3}
            placeholder="Optional context for creators seeing this card."
            style={{
              width: '100%', padding: '10px 12px', borderRadius: '9px', marginBottom: '14px', resize: 'vertical',
              background: 'var(--bg-input)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', fontSize: '13px', fontFamily: 'inherit',
            }}
          />

          <label style={{ display: 'block', fontSize: '11px', fontWeight: 700, color: 'var(--text-tertiary)', marginBottom: '6px' }}>
            <Link2 size={11} strokeWidth={2.5} style={{ display: 'inline', verticalAlign: 'middle', marginRight: '4px' }} />Link (optional)
          </label>
          <input
            value={linkUrl}
            onChange={e => setLinkUrl(e.target.value)}
            placeholder="https://…"
            style={{
              width: '100%', padding: '10px 12px', borderRadius: '9px', marginBottom: '16px',
              background: 'var(--bg-input)', border: '1px solid var(--border-color)', color: 'var(--text-primary)', fontSize: '13px',
            }}
          />

          {submitError && (
            <div style={{ padding: '8px 12px', borderRadius: '8px', background: 'rgba(239,68,68,0.1)', border: '1px solid rgba(239,68,68,0.3)', color: '#ef4444', fontSize: '12px', marginBottom: '12px' }}>
              {submitError}
            </div>
          )}

          <button
            type="submit"
            disabled={submitting}
            style={{
              display: 'flex', alignItems: 'center', gap: '6px', padding: '9px 18px', borderRadius: '9px',
              fontSize: '12.5px', fontWeight: 800, cursor: submitting ? 'not-allowed' : 'pointer',
              background: '#f97316', border: 'none', color: '#fff', opacity: submitting ? 0.7 : 1,
            }}
          >
            <Plus size={14} strokeWidth={2.5} />{submitting ? 'Adding…' : 'Add card'}
          </button>
        </form>

        {/* ── Refresh auto-generated candidates ── */}
        <div style={{
          display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '12px', flexWrap: 'wrap',
          background: 'var(--bg-card)', border: '1px solid var(--border-color)', borderRadius: '14px',
          padding: '16px 20px', marginBottom: '28px',
        }}>
          <div>
            <div style={{ fontSize: '13px', fontWeight: 800, marginBottom: '2px' }}>Story-demand &amp; audience candidates</div>
            <div style={{ fontSize: '11.5px', color: 'var(--text-muted)' }}>
              Auto-computed from trending WebMangal series and top Kalpana Circle ideas. No scheduled job yet — refresh manually.
            </div>
          </div>
          <button
            onClick={handleRefresh}
            disabled={refreshing}
            style={{
              display: 'flex', alignItems: 'center', gap: '6px', flexShrink: 0, padding: '9px 16px', borderRadius: '9px',
              fontSize: '12px', fontWeight: 700, cursor: refreshing ? 'not-allowed' : 'pointer',
              background: 'rgba(249,115,22,0.10)', border: '1px solid rgba(249,115,22,0.3)', color: '#f97316',
            }}
          >
            <RefreshCw size={13} strokeWidth={2.5} style={{ animation: refreshing ? 'spin 1s linear infinite' : 'none' }} />
            {refreshing ? 'Refreshing…' : 'Refresh now'}
          </button>
        </div>
        {refreshMsg && (
          <div style={{
            display: 'flex', alignItems: 'center', gap: '6px', marginTop: '-18px', marginBottom: '20px',
            fontSize: '12px', color: refreshMsg.startsWith('Failed') ? '#ef4444' : '#10b981',
          }}>
            {!refreshMsg.startsWith('Failed') && <CheckCircle2 size={13} strokeWidth={2} />}{refreshMsg}
          </div>
        )}

        {/* ── Existing company cards ── */}
        <h2 style={{ fontSize: '14px', fontWeight: 800, margin: '0 0 12px' }}>Company cards ({companyIdeas.length})</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', marginBottom: '28px' }}>
          {companyIdeas.length === 0 && (
            <p style={{ fontSize: '12.5px', color: 'var(--text-tertiary)' }}>No company cards yet — add one above.</p>
          )}
          {companyIdeas.map(idea => (
            <IdeaRow key={idea.id} idea={idea} onDelete={() => handleDelete(idea.id)} deleting={deletingId === idea.id} deletable />
          ))}
        </div>

        {/* ── Read-only view of auto-generated cards ── */}
        <h2 style={{ fontSize: '14px', fontWeight: 800, margin: '0 0 12px' }}>Auto-generated cards ({otherIdeas.length})</h2>
        <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
          {otherIdeas.length === 0 && (
            <p style={{ fontSize: '12.5px', color: 'var(--text-tertiary)' }}>None yet — hit &quot;Refresh now&quot; above.</p>
          )}
          {otherIdeas.map(idea => (
            <IdeaRow key={idea.id} idea={idea} onDelete={() => {}} deleting={false} deletable={false} />
          ))}
        </div>
      </div>

      <style jsx global>{`
        @keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
      `}</style>
    </div>
  );
}

function IdeaRow({ idea, onDelete, deleting, deletable }: { idea: MangalIdea; onDelete: () => void; deleting: boolean; deletable: boolean }) {
  const badge = TYPE_BADGE[idea.type];
  const Icon = badge.icon;
  return (
    <div style={{
      display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', gap: '12px',
      padding: '12px 14px', borderRadius: '11px', background: 'var(--bg-card)', border: '1px solid var(--border-color)',
    }}>
      <div style={{ minWidth: 0 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
          <span style={{
            display: 'inline-flex', alignItems: 'center', gap: '4px', fontSize: '9px', fontWeight: 800,
            color: badge.color, background: badge.bg, border: `1px solid ${badge.border}`,
            padding: '3px 8px', borderRadius: '12px', textTransform: 'uppercase', letterSpacing: '0.05em',
          }}>
            <Icon size={10} strokeWidth={2.5} />{badge.label}
          </span>
          <span style={{ fontSize: '10.5px', color: 'var(--text-muted)' }}>
            {new Date(idea.created_at).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' })}
          </span>
        </div>
        <div style={{ fontSize: '13px', fontWeight: 700, color: 'var(--text-primary)', marginBottom: idea.description ? '4px' : 0 }}>
          {idea.title}
        </div>
        {idea.description && (
          <p style={{ fontSize: '12px', color: 'var(--text-muted)', margin: 0, lineHeight: 1.4 }}>{idea.description}</p>
        )}
        {idea.link_url && (
          <a href={idea.link_url} target="_blank" rel="noopener noreferrer" style={{ fontSize: '11px', color: '#f97316', fontWeight: 700 }}>
            {idea.link_url}
          </a>
        )}
      </div>
      {deletable && (
        <button
          onClick={onDelete}
          disabled={deleting}
          style={{
            flexShrink: 0, display: 'flex', alignItems: 'center', gap: '4px', padding: '6px 10px', borderRadius: '7px',
            fontSize: '11px', fontWeight: 700, cursor: deleting ? 'not-allowed' : 'pointer',
            background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)', color: '#ef4444',
          }}
        >
          <Trash2 size={11} strokeWidth={2} />{deleting ? '…' : 'Delete'}
        </button>
      )}
    </div>
  );
}
