import { NextRequest, NextResponse } from 'next/server';
import { requireUser } from '../../../lib/auth/authedServerClient';
import { getMediaBucket } from '../../../lib/media/r2';
import { createClient } from '@supabase/supabase-js';
import { checkRateLimit } from '../../../lib/rateLimit';

// PATCH /api/user/profile — profile editor backend for K Circle settings.
// Updates creator_profiles.username / bio / avatar_url for the *calling*
// user only. Uses requireUser's user-scoped Supabase client (the caller's
// JWT on every query), so the existing RLS policies ("Users can update own
// creator profile") are the authorization layer — no service-role key and
// no hand-rolled ownership checks needed here. Pure standard fetch/Web
// APIs throughout: nothing that would strain the OpenNext Worker 3MB cap.
//
// Used only to reach the shared rate_limit_events store — same reasoning
// as every other route using checkRateLimit().
const rateLimitClient = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const BIO_MAX = 150;

// Same charset Instagram-style handles allow: lowercase letters, digits,
// dots and underscores. Profile pages live at /kalpana-circle/profile/
// <username>, so this doubles as URL-safety (no slashes/%/?/spaces).
const USERNAME_RE = /^[a-z0-9._]{3,24}$/;

// Impersonation guard for public profile URLs — deliberately short; this
// isn't a moderation system, just keeping the obvious ones out.
const RESERVED_USERNAMES = new Set(['admin', 'administrator', 'support', 'moderator', 'mangal']);

function validateUsername(raw: unknown): { ok: true; value: string } | { ok: false; error: string } {
  if (typeof raw !== 'string') return { ok: false, error: 'Username must be text.' };
  const username = raw.trim().toLowerCase();
  if (!USERNAME_RE.test(username)) {
    return {
      ok: false,
      error: 'Username must be 3-24 characters using only a-z, 0-9, dots or underscores.',
    };
  }
  if (username.startsWith('.') || username.endsWith('.')) {
    return { ok: false, error: "Username can't start or end with a dot." };
  }
  if (RESERVED_USERNAMES.has(username)) {
    return { ok: false, error: 'That username is reserved.' };
  }
  return { ok: true, value: username };
}

// Only keys generated by /api/upload-avatar are acceptable — an attacker
// with a valid session must not be able to point their avatar_url at an
// arbitrary URL (other users' objects, external hosts, data: URIs...).
function validateAvatarPath(
  raw: unknown,
  userId: string
): { ok: true; value: string | null } | { ok: false; error: string } {
  if (raw === null) return { ok: true, value: null }; // explicit removal
  if (typeof raw !== 'string') return { ok: false, error: 'Invalid avatar.' };
  const prefix = `kcircle-media/avatars/${userId}-`;
  // Key shape from upload-avatar: <prefix><ts>-<rand>.<ext>. Loosened to
  // "owned prefix + safe charset" so cosmetic generator tweaks don't break
  // validation — the security property is the userId prefix, not the tail.
  if (!raw.startsWith(prefix) || !/^[A-Za-z0-9._/-]+$/.test(raw) || raw.includes('..')) {
    return { ok: false, error: 'Invalid avatar reference.' };
  }
  return { ok: true, value: raw };
}

/** Best-effort cleanup of the replaced avatar object in R2. Non-fatal by
 * design — failing to garbage-collect an orphaned image must never fail
 * the user's actual save. */
async function deleteReplacedAvatar(oldAvatarUrl: string | null | undefined, userId: string) {
  if (!oldAvatarUrl) return;
  try {
    const parsed = new URL(oldAvatarUrl);
    const prefix = `/api/media/kcircle-media/avatars/${userId}-`;
    if (!parsed.pathname.startsWith(prefix)) return;
    const key = parsed.pathname.slice('/api/media/'.length);
    await getMediaBucket().delete(key);
  } catch {
    // Old value wasn't one of ours (or the binding isn't available, e.g.
    // plain next dev) — nothing to clean up.
  }
}

export async function PATCH(req: NextRequest) {
  const auth = await requireUser(req);
  if (!auth) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  // Modest limit: normal editing is a handful of saves a day; this mainly
  // stops username-probing loops against the uniqueness pre-check below.
  const withinLimit = await checkRateLimit(rateLimitClient, `user-profile:${auth.userId}`, 20, 60);
  if (!withinLimit) {
    return NextResponse.json({ error: 'Too many requests. Please slow down.' }, { status: 429 });
  }

  let body: { username?: unknown; bio?: unknown; avatarPath?: unknown };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid request body.' }, { status: 400 });
  }

  if (body.username === undefined && body.bio === undefined && body.avatarPath === undefined) {
    return NextResponse.json({ error: 'Nothing to update.' }, { status: 400 });
  }

  let username: string | undefined;
  if (body.username !== undefined) {
    const result = validateUsername(body.username);
    if (!result.ok) return NextResponse.json({ error: result.error }, { status: 400 });
    username = result.value;
  }

  let bio: string | null | undefined;
  if (body.bio !== undefined) {
    if (typeof body.bio !== 'string') {
      return NextResponse.json({ error: 'Bio must be text.' }, { status: 400 });
    }
    const trimmed = body.bio.trim();
    // Mirrors the client's strict 0/150 counter — defense in depth, never
    // silently truncating (the user believes what they typed was saved).
    if (trimmed.length > BIO_MAX) {
      return NextResponse.json({ error: `Bio must be ${BIO_MAX} characters or fewer.` }, { status: 400 });
    }
    bio = trimmed || null;
  }

  let avatarPath: string | null | undefined;
  if (body.avatarPath !== undefined) {
    const result = validateAvatarPath(body.avatarPath, auth.userId);
    if (!result.ok) return NextResponse.json({ error: result.error }, { status: 400 });
    avatarPath = result.value;
  }

  // Read the current row first: needed for the upsert-if-missing branch,
  // for skipping redundant writes, and to know which old avatar object to
  // garbage-collect after a successful change.
  const { data: current } = await auth.supabase
    .from('creator_profiles')
    .select('username, bio, avatar_url')
    .eq('user_id', auth.userId)
    .maybeSingle();

  // Friendly uniqueness answer before hitting the constraint; the catch of
  // Postgres 23505 below still covers the two-tab race window.
  if (username && username !== current?.username) {
    const { data: taken } = await auth.supabase
      .from('creator_profiles')
      .select('user_id')
      .eq('username', username)
      .neq('user_id', auth.userId)
      .maybeSingle();
    if (taken) {
      return NextResponse.json({ error: 'That username is already taken.' }, { status: 409 });
    }
  }

  const updates: Record<string, string | null> = {};
  if (username !== undefined && username !== current?.username) updates.username = username;
  if (bio !== undefined && bio !== (current?.bio ?? null)) updates.bio = bio;
  if (avatarPath !== undefined) {
    // Store the absolute URL (same shape uploadMediaFile always produced —
    // some call sites parse stored URLs with `new URL(...)`), built from
    // the validated owned path, not from anything client-supplied.
    const absoluteUrl =
      avatarPath === null ? null : `${new URL(req.url).origin}/api/media/${avatarPath}`;
    if (absoluteUrl !== (current?.avatar_url ?? null)) updates.avatar_url = absoluteUrl;
  }

  if (Object.keys(updates).length === 0) {
    // Nothing actually changed — succeed idempotently without a write.
    return NextResponse.json({
      profile: {
        username: current?.username ?? '',
        bio: current?.bio ?? null,
        avatar_url: current?.avatar_url ?? null,
      },
    });
  }

  let saved: { username: string; bio: string | null; avatar_url: string | null } | null;
  let saveError: string | null;

  if (!current) {
    // First-time setup: no creator_profiles row yet (the settings page has
    // always tolerated this case — a plain UPDATE would silently touch zero
    // rows). Insert instead. Fallback username mirrors katube
    // channel/connect: unique-constraint safe via the uid suffix.
    const fallbackUsername = username ?? `creator-${auth.userId.slice(0, 6)}`;
    const { data, error } = await auth.supabase
      .from('creator_profiles')
      .insert({ user_id: auth.userId, username: fallbackUsername, ...updates })
      .select('username, bio, avatar_url')
      .single();
    saved = data;
    saveError = error?.message ?? null;
  } else {
    const { data, error } = await auth.supabase
      .from('creator_profiles')
      .update(updates)
      .eq('user_id', auth.userId)
      .select('username, bio, avatar_url')
      .single();
    saved = data;
    saveError = error?.message ?? null;
  }

  if (saveError || !saved) {
    // unique_violation = lost the username race against another tab/user.
    // A clean 409 reads better than a raw postgres message in the toast.
    if (saveError?.includes('duplicate key') || saveError?.includes('23505')) {
      return NextResponse.json({ error: 'That username is already taken.' }, { status: 409 });
    }
    return NextResponse.json(
      { error: saveError || "Couldn't update profile." },
      { status: 500 },
    );
  }

  // The old avatar object is now unreferenced — remove it best-effort and
  // AFTER the DB row points at the new one (delete-first would briefly
  // serve a broken image to anyone loading the profile mid-save).
  if (updates.avatar_url !== undefined) {
    await deleteReplacedAvatar(current?.avatar_url, auth.userId);
  }

  return NextResponse.json({ profile: saved });
}